using System.Text;

var root = FindRepositoryRoot(AppContext.BaseDirectory);
var dist = Path.Combine(root, "dist");
Directory.CreateDirectory(dist);

Bundle(
    title: "SqlTestSupport runtime bundle",
    sourceRoot: Path.Combine(root, "src", "SqlTestSupport"),
    outputPath: Path.Combine(dist, "SqlTestSupport.cs"));

Bundle(
    title: "SqlTestSupport test bundle",
    sourceRoot: Path.Combine(root, "tests", "SqlTestSupport.Tests"),
    outputPath: Path.Combine(dist, "SqlTestSupport.Tests.cs"));

Console.WriteLine("Generated:");
Console.WriteLine($"  {Path.Combine(dist, "SqlTestSupport.cs")}");
Console.WriteLine($"  {Path.Combine(dist, "SqlTestSupport.Tests.cs")}");

static string FindRepositoryRoot(string start)
{
    var directory = new DirectoryInfo(start);
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "SqlTestSupport.slnx")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new InvalidOperationException("Could not find SqlTestSupport.slnx.");
}

static void Bundle(string title, string sourceRoot, string outputPath)
{
    var files = Directory
        .GetFiles(sourceRoot, "*.cs", SearchOption.AllDirectories)
        .Where(path =>
            !StringComparer.OrdinalIgnoreCase.Equals(Path.GetFileName(path), "MSTestSettings.cs") &&
            !path.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.Ordinal) &&
            !path.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.Ordinal))
        .OrderBy(path => path, StringComparer.Ordinal)
        .ToArray();

    var usings = new SortedSet<string>(StringComparer.Ordinal);
    var assemblyAttributes = new SortedSet<string>(StringComparer.Ordinal);
    var body = new StringBuilder();

    foreach (var file in files)
    {
        var relativePath = Path.GetRelativePath(sourceRoot, file).Replace(Path.DirectorySeparatorChar, '/');
        var content = File.ReadAllText(file, Encoding.UTF8).TrimStart('\uFEFF');
        var lines = content.ReplaceLineEndings("\n").Split('\n');
        var seenNamespace = false;

        body.AppendLine();
        body.AppendLine($"// BEGIN {relativePath}");

        foreach (var line in lines)
        {
            // using と assembly attribute は単一ファイル先頭へ集約。
            if (!seenNamespace && line.StartsWith("using ", StringComparison.Ordinal))
            {
                usings.Add(line.Trim());
                continue;
            }

            if (!seenNamespace && line.StartsWith("[assembly:", StringComparison.Ordinal))
            {
                assemblyAttributes.Add(line.Trim());
                continue;
            }

            if (line.StartsWith("namespace ", StringComparison.Ordinal))
            {
                seenNamespace = true;
            }

            body.AppendLine(line);
        }

        body.AppendLine($"// END {relativePath}");
    }

    var output = new StringBuilder();
    output.AppendLine("// <auto-generated>");
    output.AppendLine($"// {title}.");
    output.AppendLine("// Generated by tools/SqlTestSupport.Bootstrap.");
    output.AppendLine("// Do not edit this file directly.");
    output.AppendLine("// </auto-generated>");
    output.AppendLine("#nullable enable");
    output.AppendLine();

    foreach (var usingLine in usings)
    {
        output.AppendLine(usingLine);
    }

    if (assemblyAttributes.Count > 0)
    {
        output.AppendLine();
        foreach (var attributeLine in assemblyAttributes)
        {
            output.AppendLine(attributeLine);
        }
    }

    output.Append(body);
    File.WriteAllText(outputPath, output.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
}
